language: python
dist: xenial
python:
- 3.7
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
install:
- pip install pipenv
- pipenv install --system --deploy --ignore-pipfile
stages:
- test
- name: answers
  if: branch = master
jobs:
  include:
  - stage: test
    script: pytest --cov-report xml --cov-report term
    install:
    - pipenv install --dev --ignore-pipfile --deploy
    before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
      > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
  - stage: answers
    script:
    - python manage.py migrate
    - python manage.py load_initial_data
    - python manage.py purge_sqllite_db
env:
  global:
  - DATABASE_URL=sqlite:///data/db.sqlite
  - USE_DOCKER=no
  - secure: eiFux4/eyn+nXQQLY3Ikq4yc85zpO2E868+OUMjqNURVuEoO0VW5C+GBI0h9MYE/PUa6qOvV6k8wGi38NcWitgprYGokVxopALgPJWXscjqi8SkIVJOVhi6uHuNOhQxDHULaHeN9u22d3ETJHdF31kO8t6o4OeY4fGpHkwsq5cdVjYB51zd5rm4KIXs3ph/vih7398mJKcasgzL8mwanZoD0DAYjzWse29ZNosRfRV5XxB4q6AM9ydD/gpoTj0nBD4vcadB/5pPvIasfX62RVgu/nX4h0vDHVdIq5Ci5DvYqohjy2MpG0BIwgI33A7kgM12Fa4W1pBhBP6ZkBuRZojjBmL045dIMsDWUU53QNRzidexu7Yee4eIlErUnB7I+FWuOMaQrPslYmza3qQo1GrzPpJITkvWOpMC1YOu7M6PZq8kC4R/lnR8skxkVgfWW1ZG5TkPqtwVJIQhVIhR4Uq40YqUEzj8QXm/dfdmO4UrWlH1tbrTGiHFtDgGRdGyBs6WkVz0qg9IQ9tPKv/+lmCGG3ZUYy1vO9e7bN2iC2wmLq+lDpNbfn9m8QQTtqHNFfb09OM16xzJIv8qrNGT7WJGGoo1KdX/6gE5A4VXnJ4K31C6b5morxOIGf2F046LiRX6gCdcOrHxYE8US0KP2tRfy3Fz7usF1agGZ4Y0B1Ro=
  - secure: T4DWFdszrE4Avs7SWZRfHLZRWyaVJtXgjryfCDOsRMZe4WkvdfvKELUdsoHGPYP/gUMVCsPhrhSodTdskfqP0qIQAANXSB7+deK0QusqNNOOK7V7x+0sz66hQATgHW0lxFnFCltt0FlwDG23wD2IN7SJtbn1YEtg4YR/wWBzfyFaubCZqzTdisRmBNhCb9Vls4jtDKZhS9+49xZE3Isae8D2z3mMvNqvIEDLZK+eJ6N/9rPWEeTMaPZ32JZgPAYK9zYxp5fJXXn+Fg55erQZZbLrgpL2+GSmRioGlst1P+/XHC7x7ApP6FFohUH8KHRDGVqoCER13GQLdOE6ydFI+TFx4AleJSbgb2rxNlKpVIi2kXi5YMllwjZq5LnrPFT1RPnRy3tWhDQOhOFi52laYmqfDAkA7/nMPWgkxRJs2/ML7N1iUhDWrC7HzRZHycimZz2FQDCg0vBeOdn4ktEoORt5pRdcl38XM7hgDghPWiFjPyzoM5CCZ+DIohjS4CkZu2H629A6ex8TdLmzbGVjSkyvc1M6uIT+bJjz35+jyAGVtVUOqO9DBMGjvEdSoqd6tODMkuS21BiKm41ARMyWTcx+/l03DBb/aKmeMmpRvQlj7utgyDJfTIkZRn/0oV0YkSuS6ug9O+6UQU2zC1E3tiPv5cbjijvOazodByPjAr4=
